version: "3.9"
services:
  jenkins-server:
    image: jenkins/jenkins:lts 
    volumes:
            - jenkins:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000" 
  jenkins-worker:
    image: jenkins/agent:buster-jdk11
    init: true
    environment:
      JENKINS_URL: http://172.20.119.125:8080/computer/docker_agent/jenkins-agent.jnlp
      JENKINS_SECRET: 3d7a0d98827a596707a9d4af7421752cc47458fbb25ecef3e4eae5dee376f5d7
      WORKDIR: /home/jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: bash -c 'java -jar /usr/share/jenkins/agent.jar -jnlpUrl $$JENKINS_URL -secret $$JENKINS_SECRET -workDir $$WORKDIR'

volumes:
  jenkins: